### ISSUE TITLE
Navicat Premium 12.1.12 is not supported

### ISSUE THREAD

**Issue by xz00311** [Deltafox79/Navicat_Keygen#1]
Navicat Premium 12.1.12 is not supported ，libcc.dll error

**Comment by Deltafox79** [comment]
> Navicat Premium 12.1.12 is not supported ，libcc.dll error

What language? Work fine for me on English version.. Tested on x64..

**Comment by lengthmin** [comment]
I try the English version. this keygen works fine. 
The Chinese version can't be activated.
@xz00311 you should close the application then choose the navicat.exe

**Comment by xz00311** [comment]
The Chinese version can't be activated.  win7 SP1 x64 
![image](https://user-images.githubusercontent.com/11453691/51067784-4d34a000-1650-11e9-93fd-48aaff729145.png)

**Comment by xz00311** [comment]
I should close the application

**Comment by Hipple** [comment]
> I should close the application
您好，我也遇到了同样的问题，请问您找到解决方法了吗？ Patch的时候我已经把navicat关掉了。
有没有可能是因为我的试用期已经到期导致的这个问题？

**Comment by Hipple** [comment]
@xz00311 
您好，我也遇到了同样的问题，请问您找到解决办法了吗？我Patch的时候已经关闭navicat了

**Comment by lengthmin** [comment]
我在官方下载了英文的版本，然后破解成功了。
缺点是没有中文。
国内版可能改了点什么吧，英文版的包也比较小。

**Comment by Deltafox79** [comment]
Please only English language...

**Comment by xz00311** [comment]
@Hipple  Hello, I have the same problem. Have you found a solution? I closed Navicat when I was Patch
@lengthmin  I downloaded the English version officially and cracked it successfully.
The disadvantage is that there is no Chinese.
Maybe the domestic version has changed something, and the English version has a smaller package.

**Comment by ijrou** [comment]
> Please only English language...
Navicat Premium seems to be aimed at China proper...
I want to cry...

**Comment by Piean** [comment]
@xz00311 @Deltafox79 Hello, I have the same problem:Libcc Solution 2 -> Error. My Navicat version is Navicat Premium (Windows) version 12.1.10 x86, Language is Simplified Chinese, Operating system is windows10 1809 x64. I use Navicat_Keygen v4.2, What's wrong?

**Comment by Piean** [comment]
Oh, I am sorry, my Navicat version is 12.1.12

**Comment by LzyOnCloud** [comment]
I have tested 4.2 on 12.1.12.0 ,english version just work fine.
but chinese version will find request code decrypt error. 
hope 4.3 can break that.

**Comment by Deltafox79** [comment]
![libcc_1](https://user-images.githubusercontent.com/2518850/51182823-acecae80-18cf-11e9-8877-9182588831d2.jpg)
![libcc_2](https://user-images.githubusercontent.com/2518850/51182825-acecae80-18cf-11e9-9984-4c6a0dd21863.jpg)

**Comment by Deltafox79** [comment]
![immagine](https://user-images.githubusercontent.com/2518850/51265688-9b7fd100-19b9-11e9-9cec-4d058a90d420.jpg)

**Comment by yaochaoqc** [comment]
怎么做到的？

**Comment by Deltafox79** [comment]
Only English here.. Coming soon..

**Comment by xz00311** [comment]
@yaochaoqc 
How did you do that?

**Comment by xz00311** [comment]
Your website is hanging up. It's supposed to be a hacker attack.

**Comment by DoubleLabyrinth** [comment]
For anyone who are looking for a work round, see https://github.com/DoubleLabyrinth/navicat-keygen/issues/215#issuecomment-454787894

**Comment by ijrou** [comment]
> For anyone who are looking for a workaround, see [DoubleLabyrinth/navicat-keygen#215 (comment)](https://github.com/DoubleLabyrinth/navicat-keygen/issues/215#issuecomment-454787894)

thank you very much~ has been successful~~

**Comment by Deltafox79** [comment]
New v4.3 Online
Added Suopport for latest v12.1.12  of Navicat Premium
Thank's to DoubleLabyrinth
