### ISSUE TITLE
V5.0 is not available！！

### ISSUE THREAD

**Issue by jianzhiyao** [Deltafox79/Navicat_Keygen#10]
navicat version : 12.1.19
language : Simplified  Chinese
keygen version:v5.0

**Comment by HoldOnBro** [comment]
Navicat现在分出了国内版跟国外版了，去下国外版的然后语言选英文能激活，国内特供版激活不了的

**Comment by jianzhiyao** [comment]
> Navicat现在分出了国内版跟国外版了，去下国外版的然后语言选英文能激活，国内特供版激活不了的

感谢

**Comment by yuangezhizao** [comment]
国内版的也可以激活，亲测。
The specific version for Chinese user can be activited too.
