### ISSUE TITLE
V5.0 not work with 12.1.19

### ISSUE THREAD

**Issue by abc45628** [Deltafox79/Navicat_Keygen#11]
![TIM截图20190604102140](https://user-images.githubusercontent.com/9178345/58846718-cb9ee680-86b2-11e9-999f-11c75607a4f5.png)
#10 this issues said chinese version not work but can work with english version. So I download the english version, however, not work for me

**Comment by Dream-Mgy** [comment]
Could you give me a compiled version, Thank you

**Comment by abc45628** [comment]
https://drive.google.com/drive/folders/1UYW45sMwdap8hcswEA_RFw1-ZGcbsr_2

Install cs_x64 first, keygen error ==> install en_x64, keygen error ==>install en_x86, keygen error .
may be the install order cause the error

**Comment by Dream-Mgy** [comment]
My Navicat's version is 12.1.19 too. And I use the V5.0 it notice me  that "rsa Public key not Find". I don't know how to go next. Thank you for helping me.

**Comment by Dream-Mgy** [comment]
My Navicat's version is 12.1.19 too. And I use the V5.0 it notice me that "rsa Public key not Find". I don't know how to go next. Thank you for helping me.
![微信图片_20190606092758](https://user-images.githubusercontent.com/31054294/59000691-27e24180-883e-11e9-91f7-a049e6a7a752.png)
![微信图片_20190606092806](https://user-images.githubusercontent.com/31054294/59000693-29ac0500-883e-11e9-9763-e63770a3ed3f.png)

**Comment by Dream-Mgy** [comment]
I am so sorry that I have already used the other low version keygen. When I click the patch, it give me a notice which said I have patched already. Now I reinstall the Navicat Premium 12 again, and active it successfully.
