### ISSUE TITLE
V5.0 not work with 11.2.16 can not generate license_file

### ISSUE THREAD

**Issue by siweixiang** [Deltafox79/Navicat_Keygen#13]
V5.0 not work with Navicat Premium 11.2.16 can not generate license_file

**Comment by Deltafox79** [comment]
Can you be clearer? what does it mean that it does not generate a license? did you patch correctly? and then why don't you use the most recent 12.x.x.x? Make a screen of the steps if you can ...

**Comment by siweixiang** [comment]
select Navicat Premium 11.2.16
1. use V5.0, click the patch button, then choose the navicat.exe to be patched
2. then open navicat, click the generate button, I think then should generate serial key and license_file for activation. But, no license_file be generated.

**Comment by Deltafox79** [comment]
Copy serial generate from navicat into keygen and click generate for license file.. Load this file in navicat
