### ISSUE TITLE
rsa public key not found

### ISSUE THREAD

**Issue by lanmaster** [Deltafox79/Navicat_Keygen#19]
Some error occured on last operation.

**Comment by Deltafox79** [comment]
More details? What version of navicat? Platform? Have you tried the Patch more than once?

**Comment by lanmaster** [comment]
Navicat for PostgreSQL 12.1.22 x64 English
Windows 7 x64 Professional
Yes, i was tried the Patch more than once.

For now i removed that version and install Navicat for PostgreSQL 12.1.20 x64 English. With this version Keygen is succefully working.

**Comment by lanmaster** [comment]
Maybe i was wrong when tried to execute Patch more than once...

**Comment by Deltafox79** [comment]
![PS](https://user-images.githubusercontent.com/2518850/63206952-b5ec6b00-c0be-11e9-9753-e0c1cd3d887b.jpg)

Work for me.. have you select PostgressSql on menu dropdown at point 2?

Regards

**Comment by xiaoyouxi01** [comment]
> More details? What version of navicat? Platform? Have you tried the Patch more than once?

Navicat Premium v12.1.22 (Simplified Chinese Version)
Win7 64bit

The same error.

![01](https://user-images.githubusercontent.com/36061058/63211664-f08cec80-c12c-11e9-9b54-96a49fe5fd27.png)

![02](https://user-images.githubusercontent.com/36061058/63211665-f08cec80-c12c-11e9-944e-37240f9b9b43.png)

**Comment by Deltafox79** [comment]
As said you have select product : Premium... Change this
