### ISSUE TITLE
Can not decrypt resquest code

### ISSUE THREAD

**Issue by WinterXMQ** [Deltafox79/Navicat_Keygen#2]
![image](https://user-images.githubusercontent.com/3694982/51436220-1ef43780-1cc4-11e9-9a5f-9b21fb445b10.png)

Navicat Premium 12.1.12 Simplified Chinese.
Windows 10.

**Comment by Deltafox79** [comment]
Please use v4.4..

**Comment by wxlg1117** [comment]
@Deltafox79, use 4.4 and have same error yet...

**Comment by wxlg1117** [comment]
@Deltafox79, use 4.4 and have same error yet...

**Comment by Deltafox79** [comment]
> 
> 
> @Deltafox79, use 4.4 and have same error yet...

Hi can you test latest v4.5 and report? Thank's
