### ISSUE TITLE
Could it work with the latest release(12.1.22.0)?

### ISSUE THREAD

**Issue by Tsangkam** [Deltafox79/Navicat_Keygen#23]
I got some error while using it, thank you!

**Comment by Deltafox79** [comment]
latest release is 12.1.24 and work fine if you use 32bit try to patch many time.. 
Regards

![Immagine](https://user-images.githubusercontent.com/2518850/66153927-b4e6ad00-e61c-11e9-9ee4-1df0773593c2.jpg)
