### ISSUE TITLE
无法激活最新版navicat

### ISSUE THREAD

**Issue by anonymousAdminUser** [Deltafox79/Navicat_Keygen#24]
Navicat_Keygen_Patch_v5.3_By_DFoX无法激活navicat12.1.24版本

**Comment by anonymousAdminUser** [comment]
最后激活阶段，弹窗显示激活码无效，激活失败

**Comment by Deltafox79** [comment]
try on fresh installation... 

![Immagine](https://user-images.githubusercontent.com/2518850/67555237-2e9c2300-f711-11e9-88e4-cb17060f5342.jpg)
