### ISSUE TITLE
mac os  10.13, navicat for mysql 12.1.27采用Navicat_Keygen5.4 破解，生成秘钥正确，但是点激活之后，没有手动激动选项！无法去激活！

### ISSUE THREAD

**Issue by zhanggc** [Deltafox79/Navicat_Keygen#26]
mac os  10.13, navicat for mysql 12.1.27采用Navicat_Keygen5.4 破解，生成秘钥正确，但是点激活之后，没有手动激动选项！无法去激活！
<img width="787" alt="WX20191118-181903@2x" src="https://user-images.githubusercontent.com/1655136/69044933-c818d500-0a30-11ea-91b9-ac768a7dbb09.png">

**Comment by Deltafox79** [comment]
Try to disable internet access..
