### ISSUE TITLE
下载  v5.4  b3b8c97 v5.4 Release，打开还是 v5.0

### ISSUE THREAD

**Issue by zhanggc** [Deltafox79/Navicat_Keygen#27]
下载  v5.4  b3b8c97 v5.4 Release，打开还是 v5.0, 查看截图：
<img width="723" alt="WX20191118-183032@2x" src="https://user-images.githubusercontent.com/1655136/69045290-8b011280-0a31-11ea-9255-118d62d9e660.png">

**Comment by Deltafox79** [comment]
Please Only English and v5.5 is online..
