### ISSUE TITLE
RSA public key not found

### ISSUE THREAD

**Issue by bluesky4485** [Deltafox79/Navicat_Keygen#28]
试过最新的15及12（12.1.25），均到最后一步提示RSA public key not found，keygen试过5.4和5.3，都是一样的错误。

win10系统，64位的Navicat默认地址安装，啥情况？

**Comment by Deltafox79** [comment]
this can happen if there is a problem accessing the% temp% folder on the pc .. or if the patch did not work. try again on a clean installation of the sw ..
