### ISSUE TITLE
mac how do use it 

### ISSUE THREAD

**Issue by sujiansoft** [Deltafox79/Navicat_Keygen#4]
mac how do use it ?

**Comment by Deltafox79** [comment]
> 
> 
> mac how do use it ?

You have two way  :

> 1) Install navicat121_premium_en.dmg after start and close
> 2) Replace Navicat Premium in Crack Folder on /Applications/Navicat\ Premium.app/Contents/MacOS/
> 3) Use Navicat_Keygen_Patch_v4.7_By_DFoX.exe on windows select mac option and use RegPrivateKey.pem in crack Folder When Request..
> 
> or use Navicat_Keygen_Patch_Mac_v3.0_By_DoubleLabyrinth
[
Navicat_Mac_v12.1.15_En_x64_Incl_Crack_Keygen_v4.7_By_DFoX.zip](https://www98.zippyshare.com/v/7XGaZgYP/file.html)
[Navicat_Keygen_Patch_Mac_v3.0_By_DoubleLabyrinth.zip](https://www98.zippyshare.com/v/hsPMoyO7/file.html)

Regards
