### ISSUE TITLE
Ras Public Key Not Found!

### ISSUE THREAD

**Issue by MeteorInfinity** [Deltafox79/Navicat_Keygen#6]
![TIM截图20190315000443](https://user-images.githubusercontent.com/14803701/54372492-612f6900-46b6-11e9-83e9-e899e3a73776.png)
![TIM截图20190315000543](https://user-images.githubusercontent.com/14803701/54372494-612f6900-46b6-11e9-8bfc-c54315a38342.png)
Something wrong like this when cracked the navicat 12.1.16, and I don't know how to do.

**Comment by Deltafox79** [comment]
What version of Patch you use?

**Comment by STC214** [comment]
keep ur version be newest and close ur Anti-virus

**Comment by MeteorInfinity** [comment]
v4.9
and navicat is 12.1.16  x64
my system is Widows10 x64

**Comment by MeteorInfinity** [comment]
I switch navicat to the x86 version, and after a failure,  its worked.

**Comment by BudSun** [comment]
I also encountered this problem just now, but I solved it by completely uninstalling.
