### ISSUE TITLE
Data Modeler can use it ?(Mac version)

### ISSUE THREAD

**Issue by qinkangdeid** [Deltafox79/Navicat_Keygen#7]
Data Modeler soft can use it ?
I am use mac machine.
thanks.

**Comment by Deltafox79** [comment]
If you know how Load the license file yes.. In Windows just use shift + click on activate button for Load license file..

**Comment by ClubACNews** [comment]
Where is stocked the license_file on a windows 7/64 bits ? I use the instal Data modeler 2.1.18 french. Thanks

**Comment by q447552640** [comment]
> If you know how Load the license file yes.. In Windows just use shift + click on activate button for Load license file..

In Windows I did not find the license file

**Comment by Deltafox79** [comment]
For Mac just copy the license file on Desktop
