### ISSUE TITLE
Can not find generated "license_file"

### ISSUE THREAD

**Issue by dirgaharjuna** [Deltafox79/Navicat_Keygen#8]
I tried to path Navicat Data Modeler using Keygen v5.0 on windows 10. I patched the file and generate the serial keygen with no problem. But after that I need the generated 'license_file' which I can't find it anywhere on my pc (I looked in the same directory where the keygen is and also desktop). Where do I supposed to look for that file? Thanks.

**Comment by Deltafox79** [comment]
If you select Modeler in Patch section, when you click generate button, the patch It will ask you for the folder where to save the license

**Comment by dirgaharjuna** [comment]
Oh, I thought I just have to click the first generate button since it already give me the serial key, but apparently I have to click both generate button (the one at the left corner footer is the one that ask me where to save the license), my bad. It's working like a charm now. Thanks for helping.
